"""Field definitions for the EOSE Financials Definitions tab."""

from __future__ import annotations

FINANCIALS_DEFINITIONS_SHEET = "Financials Definitions"

FIELD_NOTES: dict[str, str] = {
    "Units": "Column B header. Each metric row has a unit here; time series start at column C.",
    "Year": "Calendar year of the quarter column (2025–2030).",
    "Quarter": "Fiscal quarter 1–4. Eos reports on a calendar quarter.",
    "Quarter ending": "EOMONTH of the quarter. Used for years-from-present and Stock price lookup.",
    "As of date": "Single date in C. Years from present = (quarter ending − this) / 365. Update after each earnings print.",
    "Years from present": "Discount tenor for present-value stock price. Formula from quarter ending vs As of date.",
    "Pipeline": "Commercial opportunity pipeline ($B) as disclosed. Proposals + LOI; excludes lead-gen. Actual only.",
    "Pipeline - Model": "Carries last actual forward. Edit a future cell to assume pipeline growth.",
    "Pipeline (GWh)": "Pipeline energy (GWh) when Eos discloses it.",
    "Pipeline (GWh) - Model": "Carries last actual GWh forward.",
    "Booked orders": "New orders in the quarter ($M). Disclosed when available (e.g. Q4 2025 $240M); otherwise implied as Δbacklog + revenue.",
    "Booked orders - Model": "Default: last actual booked orders carried forward. Primary demand assumption.",
    "Backlog": "Ending backlog ($M). Company identity: prior + orders − shipments.",
    "Backlog - Model": "Prior (actual if present else model) + orders (actual if present else model) − revenue (actual if present else model).",
    "Backlog (GWh)": "Ending backlog energy (GWh) as disclosed.",
    "Backlog (GWh) - Model": "Same roll as dollar backlog using GWh shipped - Model and implied GWh orders (dollar orders / ASP).",
    "Backlog conversion lag": "Quarters of beginning backlog assumed convertible this quarter. Default 4. Caps GWh shipped - Model together with factory capacity.",
    "GWh shipped": "Energy shipped / recognized in the quarter when disclosed. Often blank — revenue is the better actual.",
    "GWh shipped - Model": "MIN(factory capacity, beginning backlog GWh / conversion lag).",
    "Z3 ASP": "Average selling price ($/kWh) when derived or disclosed. Usually blank.",
    "Z3 ASP - Model": "Assumption: $250 early 2025, $256 thereafter. Revenue - Model = GWh shipped - Model × ASP.",
    "Z3 Module Energy Capacity": "kWh per Z3 module (product sheet ~1.2 kWh). Scalar in C, copied across.",
    "Z3 module cycle time": "Reported cycle time when disclosed (Line 2 ~10% faster vs Line 1 in Q2 2026).",
    "Z3 module cycle time - Model": "Starts at 18s; compounds at the quarterly reduction rate; floored at Cycle time floor (C).",
    "Quarterly module cycle time reduction rate": "Learning-curve % per quarter (default 2.9). Guess — not disclosed as a rate.",
    "Cycle time floor": "Seconds. Model cycle time will not go below this (default 10).",
    "Z3 modules per cube": "Modules per Cube (672). Scalar.",
    "Z3 manufacturing lines": "Installed lines when known (1 through Q1 2026; 2 from Q2 2026 Line 2 launch).",
    "Z3 manufacturing lines - Model": "Editable ramp (1 → 12). Capacity ceiling, not a demand forecast.",
    "Capacity utilization": "Utilization % assumption (default 85). Apply to Model lines.",
    "Z3 manufacturing lines utilized - Model": "Lines - Model × utilization.",
    "Full utilization weeks per year": "365/7.",
    "Full utilization days per week": "Default 7.",
    "Full utilization hours per day": "Default 24.",
    "Module production count per line - Model": "Seconds in a year / cycle time / 1e6.",
    "Capacity per line - Model": "kWh/module × modules per line × utilization.",
    "Annualized module energy capacity - Model": "Capacity per line × lines (nameplate, not utilized).",
    "Factory capacity - Model": "Quarterly GWh = annualized nameplate / 4.",
    "Unit COGS - Model": "Explicit thesis ($160/kWh). Not calibrated to today’s −70% gross margin — Actual COGS shows the gap.",
    "45x & active electrode credits": "$/kWh statutory credit assumption (default 47).",
    "45x transfer rate": "% of credit realized (default 90).",
    "Effective 45x credit - Model": "Credit × transfer rate.",
    "Government credits - Model": "Effective credit × GWh shipped - Model. Applied as a COGS offset only — not added to revenue.",
    "Unit COGS w/ 45x - Model": "Unit COGS − effective 45X.",
    "FY 2026 revenue guidance — low": "Management FY2026 revenue guide low ($300M as of Q2 2026). Scalar in C.",
    "FY 2026 revenue guidance — high": "Management FY2026 revenue guide high ($350M as of Q2 2026). Scalar in C.",
    "Revenue": "GAAP / earnings-release total revenue ($M). Hardcoded actuals through last print.",
    "Revenue - Model": "GWh shipped - Model × Z3 ASP - Model. Does not add 45X credits.",
    "COGS": "GAAP cost of goods sold ($M).",
    "COGS - Model": "Unit COGS × GWh shipped - Model − government credits.",
    "Gross profit": "Reported gross profit (loss).",
    "Gross profit - Model": "Revenue - Model − COGS - Model.",
    "Gross margin": "Gross profit / Revenue × 100 when Revenue actual is present.",
    "Gross margin - Model": "Gross profit - Model / Revenue - Model × 100.",
    "SG&A": "Selling, general & administrative ($M).",
    "SG&A - Model": "Carries last actual SG&A forward (opex hold, OPEN-style).",
    "R&D": "Research & development ($M).",
    "R&D - Model": "Carries last actual R&D forward.",
    "OpEx": "Total operating expenses when disclosed; else SG&A + R&D.",
    "OpEx - Model": "SG&A - Model + R&D - Model.",
    "Adjusted EBITDA": "Company-defined adjusted EBITDA ($M). Actuals from earnings reconciliations.",
    "Adjusted EBITDA - Model": "Gross profit - Model − OpEx - Model.",
    "Adjusted EBITDA margin": "Adj. EBITDA / Revenue × 100.",
    "Adjusted EBITDA margin - Model": "Adj. EBITDA - Model / Revenue - Model × 100.",
    "Annualized EBITDA - Model": "Adj. EBITDA - Model × 4. Used only if positive in the EV formula.",
    "GAAP net income": "Net income (loss) attributable to shareholders. Dominated by warrant/derivative FV marks — do not treat as operating.",
    "GAAP net income - Model": "Adj. EBITDA - Model − net interest run-rate. Intentionally ignores FV marks.",
    "Cash": "Cash + restricted cash ($M) as disclosed.",
    "Cash - Model": "Prior cash (actual if present else model) + Adj. EBITDA - Model − capex − interest run-rate.",
    "Capex - Model": "Capex per incremental line × MAX(0, Δ lines - Model).",
    "Capex per incremental line": "Guess ($40M). 2025 investing cash outflow was ~$55M for the year.",
    "Net interest run-rate": "Quarterly net interest assumption ($12M from Q2 2026 interest expense order of magnitude).",
    "Long term debt": "Reported long-term debt when entered.",
    "Total debt": "Reported total debt when entered.",
    "Total debt - Model": "Carries last actual total debt, else $1,000M placeholder.",
    "Net debt - Model": "Total debt - Model − Cash (actual if present else model).",
    "Basic shares": "Shares outstanding / basic weighted average (million).",
    "Fully diluted shares": "Diluted weighted average or fully diluted count (million) from the 10-Q.",
    "Fully diluted shares - Model": "Last actual diluted shares carried forward. Add events on the Shares tab when you want incremental dilution.",
    "Stock price": "Last daily close on or before quarter-end from Price History (GOOGLEFINANCE).",
    "Market cap": "Stock price × diluted shares / 1000 ($B).",
    "EV / EBITDA": "Multiple applied only when annualized EBITDA - Model is positive (default 30).",
    "Discount rate": "Annual discount rate for PV of implied future price (default 20%).",
    "Enterprise value - Model": "IF(annualized EBITDA > 0, annualized EBITDA × EV/EBITDA / 1000, blank) in $B.",
    "Market cap - Model": "Enterprise value − net debt / 1000.",
    "Implied future stock price - Model": "Market cap - Model / diluted shares × 1000.",
    "Present stock price discounted - Model": "-PV(discount rate, years from present, 0, implied future price).",
}
